#ifndef FINALCHECKERS_STATE_H
#define FINALCHECKERS_STATE_H


#include "Side.h"

enum State {
EMPTY,WHITE=WHITE_SIDE,BLACK=BLACK_SIDE,WHITE_QUEEN = WHITE_SIDE_QUEEN,BLACK_QUEEN = BLACK_SIDE_QUEEN
};


#endif //FINALCHECKERS_STATE_H
